### ISSUE TITLE
Updated variant annotation table for SCHEMA

### ISSUE THREAD

**Issue by TarjinderSingh** [broadinstitute/exome-results-browsers#22]
`gs://schizophrenia/browser-5/2020-09-10_schema-browser-variant-annotation-table.ht`

I've added a column called canonical_term which is the string label for the consequence. However, I kept canonical_csq such that you know which variants are lof, mis, etc.

It would be good to have missense variants still separated into MPC 2 - 3 and MPC > 3. I think you do that as part of your processing pipeline?

Let me know if this makes sense.

Thanks!

**Comment by nawatts** [comment]
Yes, the browser data pipeline handles splitting up missense variants by MPC value.

https://github.com/broadinstitute/exome-results-browsers/blob/ccae47fa2ed23f602865df438978ac3774b4d477/data_pipeline/data_pipeline/datasets/schema/schema_variant_results.py#L31-L34
