### ISSUE TITLE
LoF label changed to PTV

### ISSUE THREAD

**Issue by TarjinderSingh** [broadinstitute/exome-results-browsers#25]
Not sure how to best systematically do this just for the SCHEMA browser, but in the gene page, we have LoF for:

1. The variant selection button
2. Constraint definition

For some reason, we have decided to use PTV in the SCHEMA project - what is the easiest to make all the PTV consistent?

**Comment by nawatts** [comment]
1. The consequence categories are shared between all browsers, so it's not easy to change labels there. Also, the variant annotations data does call those variants "loss of function" in the `csq_canonical` field.

2. The constraint table is also shared between all browsers. The constraint data also calls that category "lof" (it's shown as "pLoF" in the gnomAD browser) so I'm reluctant to rename it here.

**Comment by TarjinderSingh** [comment]
Works for me!

**Comment by TarjinderSingh** [comment]
We can even add that in the description (question mark).

**Comment by TarjinderSingh** [comment]
Metrics for quantification intolerance to protein-truncating variation as calculated by the gnomAD consortium. For more information, please visit the gnomAD browser. Please note that insertions and deletions are excluded in the aggregated counts and calculated metrics. Here, instead of PTV, the gnomAD browser uses LoF, which is by definition equivalent to PTV.
